<!--JOSE VELAZQUEZ
MODULE 7.2 ASSIGNMENT
DATE: 07/12/2026
This page inserts a new movie record into the database.-->


<%@ page import="java.util.List" %>
<%@ page import="com.csd430.JoseMovieBean" %>
<%@ page import="com.csd430.JoseMovieBean.MovieRecord" %>
<%--
    Jose Velazquez
    Project Part 2 JSP Page
    This page receives the form input, inserts the new movie record, and displays all records.
--%>
<%
    String message = "";
    String title = request.getParameter("title");
    String genre = request.getParameter("genre");
    String releaseYearValue = request.getParameter("releaseYear");
    String director = request.getParameter("director");
    String rating = request.getParameter("rating");

    if (title != null && genre != null && releaseYearValue != null && director != null && rating != null) {
        int releaseYear = Integer.parseInt(releaseYearValue);
        JoseMovieBean.addMovie(title, genre, releaseYear, director, rating);
        message = "The new movie record was added successfully.";
    }

    List<MovieRecord> movies = JoseMovieBean.getAllMovies();
%>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie Records</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <main>
        <h1>All Movie Records</h1>
        <p class="success"><%= message %></p>
        <p>
            The table below displays every record currently held in the jose_movies_data table.
            The new key value is generated by MySQL and appears in the Movie ID column.
        </p>

        <h2>Field Descriptions</h2>
        <p>
            Movie ID is the primary key. Title stores the movie name. Genre stores the movie category.
            Release Year stores the year released. Director stores the movie director. Rating stores the content rating.
        </p>

        <table>
            <thead>
                <tr>
                    <th>Movie ID</th>
                    <th>Title</th>
                    <th>Genre</th>
                    <th>Release Year</th>
                    <th>Director</th>
                    <th>Rating</th>
                </tr>
            </thead>
            <tbody>
                <%
                    for (MovieRecord movie : movies) {
                %>
                <tr>
                    <td><%= movie.getMovieId() %></td>
                    <td><%= movie.getTitle() %></td>
                    <td><%= movie.getGenre() %></td>
                    <td><%= movie.getReleaseYear() %></td>
                    <td><%= movie.getDirector() %></td>
                    <td><%= movie.getRating() %></td>
                </tr>
                <%
                    }
                %>
            </tbody>
        </table>

        <p><a href="joseAddMovie.jsp">Add Another Movie Record</a></p>
        <p><a href="index.jsp">Back to Project Index</a></p>
    </main>
</body>
</html>
