<!--JOSE VELAZQUEZ
MODULE 7.2 ASSIGNMENT
DATE: 07/12/2026
This page provides a form for adding a new movie record to the database.-->


<%--
    Jose Velazquez
    Project Part 2 JSP Page
    This page provides a form for adding a new movie record to the database.
    The primary key value is generated by MySQL after the form is submitted.
--%>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Movie Record</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <main>
        <h1>Add a New Movie Record</h1>
        <p>
            This form adds a new record to the jose_movies_data table in the CSD430 database.
            The movie ID is the primary key and will be created automatically when the form is submitted.
        </p>

        <h2>Record Description</h2>
        <p>
            The movie record includes a title, genre, release year, director, and rating.
            After submitting the form, all records in the table will be displayed.
        </p>

        <form action="joseInsertMovie.jsp" method="post">
            <label for="title">Movie Title:</label>
            <input type="text" id="title" name="title" maxlength="100" required>

            <label for="genre">Genre:</label>
            <input type="text" id="genre" name="genre" maxlength="50" required>

            <label for="releaseYear">Release Year:</label>
            <input type="number" id="releaseYear" name="releaseYear" min="1888" max="2100" required>

            <label for="director">Director:</label>
            <input type="text" id="director" name="director" maxlength="100" required>

            <label for="rating">Rating:</label>
            <select id="rating" name="rating" required>
                <option value="G">G</option>
                <option value="PG">PG</option>
                <option value="PG-13">PG-13</option>
                <option value="R">R</option>
                <option value="NR">NR</option>
            </select>

            <button type="submit">Add Movie Record</button>
        </form>

        <p><a href="index.jsp">Back to Project Index</a></p>
    </main>
</body>
</html>
