/**
JOSE VELAZQUEZ
MODULE 8.2 ASSIGNMENT
DATE: 07/19/2026
JavaBean used by the JSP pages to read movie records from the CSD430 database.
The bean connects to the jose_movies_data table using the student1 account.
*/


package com.csd430;

import java.io.Serializable;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * JoseMovieBean is a JavaBean used by the JSP pages to connect to the
 * CSD430 database and retrieve or add records in the jose_movies_data table.
 */
public class JoseMovieBean implements Serializable {
    private static final long serialVersionUID = 1L;

    private static final String DB_URL = "jdbc:mysql://localhost:3306/CSD430";
    private static final String DB_USER = "student1";
    private static final String DB_PASSWORD = "pass";

    /**
     * Opens and returns a connection to the CSD430 MySQL database.
     *
     * @return database connection
     * @throws SQLException if the database connection fails
     */
    private static Connection getConnection() throws SQLException {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            throw new SQLException("MySQL JDBC Driver was not found.", e);
        }
        return DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
    }

    /**
     * Gets all primary key values from the movie table for the dropdown menu.
     *
     * @return list of movie_id values
     * @throws SQLException if the query fails
     */
    public static List<Integer> getMovieKeys() throws SQLException {
        List<Integer> movieKeys = new ArrayList<>();
        String sql = "SELECT movie_id FROM jose_movies_data ORDER BY movie_id";

        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                movieKeys.add(rs.getInt("movie_id"));
            }
        }
        return movieKeys;
    }

    /**
     * Gets one movie record based on the selected primary key value.
     *
     * @param movieId selected movie_id value
     * @return MovieRecord object or null if no record is found
     * @throws SQLException if the query fails
     */
    public static MovieRecord getMovieById(int movieId) throws SQLException {
        String sql = "SELECT movie_id, title, genre, release_year, director, rating "
                + "FROM jose_movies_data WHERE movie_id = ?";

        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, movieId);

            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return new MovieRecord(
                            rs.getInt("movie_id"),
                            rs.getString("title"),
                            rs.getString("genre"),
                            rs.getInt("release_year"),
                            rs.getString("director"),
                            rs.getString("rating")
                    );
                }
            }
        }
        return null;
    }

    /**
     * Adds a new movie record to the database. The movie_id is generated by MySQL.
     *
     * @param title movie title
     * @param genre movie genre
     * @param releaseYear release year
     * @param director movie director
     * @param rating movie rating
     * @throws SQLException if the insert fails
     */
    public static void addMovie(String title, String genre, int releaseYear, String director, String rating)
            throws SQLException {
        String sql = "INSERT INTO jose_movies_data (title, genre, release_year, director, rating) "
                + "VALUES (?, ?, ?, ?, ?)";

        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, title);
            pstmt.setString(2, genre);
            pstmt.setInt(3, releaseYear);
            pstmt.setString(4, director);
            pstmt.setString(5, rating);
            pstmt.executeUpdate();
        }
    }

    /**
     * Gets all movie records for displaying the full table after a new record is added.
     *
     * @return list of MovieRecord objects
     * @throws SQLException if the query fails
     */
    public static List<MovieRecord> getAllMovies() throws SQLException {
        List<MovieRecord> movies = new ArrayList<>();
        String sql = "SELECT movie_id, title, genre, release_year, director, rating "
                + "FROM jose_movies_data ORDER BY movie_id";

        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                movies.add(new MovieRecord(
                        rs.getInt("movie_id"),
                        rs.getString("title"),
                        rs.getString("genre"),
                        rs.getInt("release_year"),
                        rs.getString("director"),
                        rs.getString("rating")
                ));
            }
        }
        return movies;
    }


    /**
     * Updates an existing movie record in the database. The movie_id is not changed.
     *
     * @param movieId selected movie_id primary key
     * @param title updated movie title
     * @param genre updated movie genre
     * @param releaseYear updated release year
     * @param director updated movie director
     * @param rating updated movie rating
     * @throws SQLException if the update fails
     */
    public static void updateMovie(int movieId, String title, String genre, int releaseYear, String director, String rating)
            throws SQLException {
        String sql = "UPDATE jose_movies_data "
                + "SET title = ?, genre = ?, release_year = ?, director = ?, rating = ? "
                + "WHERE movie_id = ?";

        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, title);
            pstmt.setString(2, genre);
            pstmt.setInt(3, releaseYear);
            pstmt.setString(4, director);
            pstmt.setString(5, rating);
            pstmt.setInt(6, movieId);
            pstmt.executeUpdate();
        }
    }

    /**
     * Simple record class used to hold one row from the jose_movies_data table.
     */
    public static class MovieRecord implements Serializable {
        private static final long serialVersionUID = 1L;

        private int movieId;
        private String title;
        private String genre;
        private int releaseYear;
        private String director;
        private String rating;

        public MovieRecord(int movieId, String title, String genre, int releaseYear, String director, String rating) {
            this.movieId = movieId;
            this.title = title;
            this.genre = genre;
            this.releaseYear = releaseYear;
            this.director = director;
            this.rating = rating;
        }

        public int getMovieId() {
            return movieId;
        }

        public String getTitle() {
            return title;
        }

        public String getGenre() {
            return genre;
        }

        public int getReleaseYear() {
            return releaseYear;
        }

        public String getDirector() {
            return director;
        }

        public String getRating() {
            return rating;
        }
    }
}
